name: Python CI

on:
  push:
    branches:
      - main
      - lab03
    paths:
      - "app_python/**"
  pull_request:
    branches:
      - main
      - lab03
    paths:
      - "app_python/**"

jobs:
  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
