name: Python CI

on:
  push:
    branches:
      - main
      - lab03
    paths:
      - "app_python/**"
  pull_request:
    branches:
      - main
      - lab03
    paths:
      - "app_python/**"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    env:
      CACHE_DIR: /home/runner/.cache/pip
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}-pip-${{ hashFiles('app_python/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0

      - name: Install dependencies
        working-directory: app_python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        working-directory: app_python
        run: |
          black . --line-length=79
          flake8 .

      - name: Tests
        run: |
          pytest .
